config/routes.rb
TrelloBoard::Application.routes.draw do

  root to: "main#index"
  resource :root, only: [:index]

  resource :session, only: [:new, :create, :destroy]
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "register" => "sessions#register"

  # resources :users, only: [:show]

  namespace :api do
    resources :users, only: [:show] do
      collection do
        get :current
      end
    end

    resources :boards, only: [:index, :show, :create, :update]

    resources :lists , except: [:edit] do
      collection do
        post :sort
      end
    end

    resources :cards, except: [:edit] do
      collection do
        post :sort
      end
    end

    resources :card_comments, only: [:index, :create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trello Board</title>
  <%= favicon_link_tag "/favicon.ico" %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">

  <div class="github-fork-ribbon-wrapper right">
    <div class="github-fork-ribbon">
        <a href="https://github.com/framgia/trello-board/tree/develop">Copyright ICT58</a>
    </div>
  </div>

  <div id="header">
    <div class="header-logo">
      <h1><a href="#/">TRELLO BOARD<span>ICT Project Management Tool</span></a></h1>
    </div>
    <div class="header-user">
      <% if logged_in? %>
        <p>(<%= link_to "Logout", logout_url %>)</p>
      <% else %>
        <p><%= link_to "Login", login_url %></p>
      <% end %>
       <% if logged_in? %>
        <p>(<%= link_to "Register", register_url %>)</p>
      <% else %>
        <p><%= link_to "Register", register_url %></p>
      <% end %>
    </div>
  </div>

  <div id="main clearfix">
    <%= yield %>
  </div>

  <div id="footer">
    <p>
      Trello Board is a project created by ICT58.
    </p>
  </div>
</div>

</body>
</html>